title: Dutch Vaccination Profiles
description: Understanding heterogeneity in vaccination decisions in the Netherlands.
show_downloads: false
theme: jekyll-theme-minimal

exclude:
  - LICENSE
  - README.md
  - run.sh

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
